# Site settings
site: n4.sk
title: n4.sk - Frantisek Nagy
keywords: nagy, blog
description: >-
  n4.sk - Frantisek Nagy
lang: hu-HU
timezone:  Europe/Bratislava
#repo: https://github.com/onepase/Ephesus # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
#google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Frantisek Nagy
  bio: 3D printing, Open Source /#linux
  picture: assets/images/avatar.png
  github: nagyfrankie # github username
#  twitter: onepase # twitter username
  facebook: nfrantisek # facebook username
#  instagram: onepase # instagram username
#  youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
#  linkedin: hakantorun # linkedin username
  email: hello@n4.sk # email adress


# URL settings
url: "https://n4.sk" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false